GWS/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.views.decorators.cache import cache_page
import cross
import account

CACHE_TTL = getattr(settings, 'CACHE_TTL')

urlpatterns = ([
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cross/', include('cross.urls')),
    # url(r'^compress/', cross.views.compressImage),
    url(r'^place_list/$', cache_page(CACHE_TTL)(cross.views.place_list.as_view()), name="place_list"),
    url(r'^picture_list/$', cache_page(CACHE_TTL)(cross.views.picture_list.as_view()), name="picture_list"),
    url(r'^add_place/$', cross.views.add_place.as_view(), name="add_place"),
    url(r'^add_picture/$', cache_page(CACHE_TTL)(cross.views.add_picture.as_view()), name="add_picture"),
    url(r'^laboratory/$', cross.views.laboratory.as_view(), name="laboratory"),
    url(r'^similar_pictures/$', cross.views.similar_pictures),
    url(r'^place_show/(?P<id>\d+)/$', cross.views.place_show.as_view(), name="place_show"),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('^$',cache_page(CACHE_TTL)(cross.views.home), name="home"),
    url('^account/', include('account.urls', namespace='account'))
]) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = cross.views.page_not_found

account/urls.py
from django.conf.urls import patterns, url
from account import views

 
urlpatterns = patterns('',
    url(r'^$', views.sign_in, name='sign_in'),
    url(r'^sign_up/$',views.sign_up, name='sign_up'),
)

account/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    email = models.EmailField()
    password = models.CharField(max_length=50)


    def __str__(self):
        return self.email

account/views.py
from django.shortcuts import render

from django import forms
from django.shortcuts import render_to_response
from django.http import HttpResponse,HttpResponseRedirect
from django.template import RequestContext
from account.models import User
from django.views.decorators.csrf import csrf_exempt

class UserForm(forms.Form):
    email = forms.EmailField(label='email')
    password = forms.CharField(label='password',widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
        })


@csrf_exempt
def sign_in(request):
    if request.method == "POST":
        uf = UserForm(request.POST)
        if uf.is_valid():
            email = uf.cleaned_data['email']
            password = uf.cleaned_data['password']
            user = User.objects.filter(email=email, password=password)
            if user: 
                tip = "登录成功"
                return render_to_response('sign_in.html', {'uf':uf, 'tip':tip})
            else:
                tip = "邮箱或密码不对"
                return render_to_response('sign_in.html', {'uf':uf, 'tip':tip})
    else:
        uf = UserForm()
    return render_to_response('sign_in.html', {'uf':uf})


@csrf_exempt
def sign_up(request):
    if request.method == "POST":
        uf = UserForm(request.POST)
        if uf.is_valid():
            email = uf.cleaned_data['email']
            password = uf.cleaned_data['password']

            user = User.objects.get(email=email)
            if user:
                tip = "这个邮箱已经被注册了"
                return render_to_response('sign_up.html', {'uf':uf, 'tip':tip})
            else:
                user = User()
                user.email = email
                user.password = password           
                user.save()
                tip = "注册成功，去登录试试看"
                return render_to_response('sign_up.html',{'uf':uf, 'tip':tip})
    else:
        uf = UserForm()
    return render_to_response('sign_up.html',{'uf':uf})

account/templates/sign_in.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">

  {% include "nav.html" %}
  <script type="text/javascript">
    $(document).ready(function(){
      $("#nav_sign_in").attr("class", "active");
    });
  </script>
  
  <div class="row">  
    <form class="col-sm-offset-3 col-md-offset-3" method="post" enctype="multipart/form-data">  
      <h3 class="form-title">登录</h3>  
      <div class="col-sm-9 col-md-9">  
        {{uf.as_p}}
        <div class="form-group">  
          <label class="checkbox">  
          <input type="checkbox" name="remember" value="1"/> Remember me  </label>  
          <hr />  
          <a href="{% url 'account:sign_up' %}" id=sign_up_btn" class="">Create an account</a>  
        </div>  
        <div class="form-group">  
          <input type="submit" class="btn btn-success pull-right" value="Login "/>     
        </div>  
      </div>
    </form>
  </div>
  <p></p>
  {% if tip %}
  <div class="row">
    <div class="col-sm-8 col-md-4 col-md-offset-4 alert alert-success">
      {{tip}}
    </div>
  </div>
  {% endif %}
</div>

{% endblock %}

account/templates/sign_up.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">

  {% include "nav.html" %}
  <script type="text/javascript">
    $(document).ready(function(){
      $("#nav_sign_in").attr("class", "active");
    });
  </script>
  
  <div class="row">  
    <div class="col-sm-2 col-md-3"></div>
    <div class="col-sm-8 col-md-6">
      <form method="post" enctype="multipart/form-data">  
        <h3 class="form-title">新用户注册</h3>  
          {{uf.as_p}}
          <div class="form-group">
            <label for="checkpwd">再次确认密码</label>
            <input type="password" class="form-control" id="checkpwd">
          </div>
          <div class="form-group">  
            <input type="submit" class="btn btn-success pull-right" value="注册"/>     
          </div>  
      </form>
    </div>
    <div class="col-sm-2 col-md-3"></div>
  </div>
  <p></p>
  {% if tip %}
  <div class="row">
    <div class="col-sm-8 col-md-4 col-md-offset-4 alert alert-success">
      {{tip}}
    </div>
  </div>
  {% endif %}
</div>

{% endblock %}

account/templates/success.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title></title>
</head>
<body>
    <h1>恭喜{{username}},注册成功！</h1>
</form>
</body>
</html>