GWS/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.views.decorators.cache import cache_page
import cross
import account

CACHE_TTL = getattr(settings, 'CACHE_TTL')

urlpatterns = ([
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cross/', include('cross.urls')),
    # url(r'^compress/', cross.views.compressImage),
    url(r'^place_list/$', cache_page(CACHE_TTL)(cross.views.place_list.as_view()), name="place_list"),
    url(r'^picture_list/$', cache_page(CACHE_TTL)(cross.views.picture_list.as_view()), name="picture_list"),
    url(r'^add_place/$', cross.views.add_place.as_view(), name="add_place"),
    url(r'^add_picture/$', cache_page(CACHE_TTL)(cross.views.add_picture.as_view()), name="add_picture"),
    url(r'^laboratory/$', cross.views.laboratory.as_view(), name="laboratory"),
    url(r'^similar_pictures/$', cross.views.similar_pictures),
    url(r'^place_show/(?P<id>\d+)/$', cross.views.place_show.as_view(), name="place_show"),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('^$',cache_page(CACHE_TTL)(cross.views.home), name="home"),
    url('^account/', include('account.urls', namespace='account'))
]) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = cross.views.page_not_found

account/urls.py
from django.conf.urls import patterns, url
from account import views

 
urlpatterns = patterns('',
    url(r'^$', views.sign_in, name='sign_in'),
    url(r'^sign_up/$',views.sign_up, name='sign_up'),
)

cross/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.routers import DefaultRouter, SimpleRouter
from . import views

router = DefaultRouter()
router.register(r'place', views.PlaceViewSet)
router.register(r'picture', views.CrossPictureViewSet)
router.register(r'place/(?P<name>.+)/$', views.PlaceViewSet)

urlpatterns = router.urls

cross/models.py
# -*- coding: utf-8 -*-
from django.db import models
import json
import urllib
import requests
from pip._vendor.requests.exceptions import HTTPError
from difflib import Match


class Place(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    longitude = models.FloatField()
    latitude = models.FloatField()
    altitude = models.FloatField(default=0.0)
    city = models.ForeignKey("City", blank=True, null=True)

    def __str__(self):
        if not self.city:
            print('look up')
            self.city = self.look_up_city(self.latitude, self.longitude)
            self.save()
        if not self.city:
            city = City.objects.get_city('No City Match', city_code=000000)
            self.city = city
            self.save()
        return '的'.join([str(self.city.province.name + self.city.name), self.name])

    @property
    def cross_pictures(self):
        return self.crosspicture_set.all()

    @staticmethod
    def look_up_city(latitude, longitude):
        url = ('http://api.map.baidu.com/geocoder/v2/?'
               'ak=IiiPZfBRZ8PIWlMPF2tc4vnWZtxSvWIQ'
               '&coordtype=wgs84ll'
               '&callback=renderReverse&location={},{}'
               '&output=json'
               '&pois=0').format(latitude, longitude)
        r = requests.request(
            method="get",
            url=url,
        )
        for i in range(3):
            try:
                r.raise_for_status()
                text = r.text
                break
            except HTTPError as e:
                text = None
        if text:
            try:
                result_dict = json.loads(text[29:-1])
                address_component = result_dict['result']['addressComponent']
                print(address_component)
                city_name = address_component['city']
                province_name = address_component['province']
                country_name = address_component['country']
                city_code = result_dict['result']['cityCode']
                if not city_name:
                    city_name = "NONE_NAME_CITY: {}".format(city_code)
                city = City.objects.get_city(
                    city_name, city_code, province_name, country_name)
#                 self.city = city

            except:
                pass
        return city


class CrossPicture(models.Model):
    title = models.CharField(max_length=100)
    picture = models.ImageField(
        upload_to='cross_picture', blank=True, null=True)
    datetime = models.DateTimeField()
    time_str = models.CharField(max_length=100)
    detail_url = models.CharField(max_length=255, blank=True, null=True)
    detail_title = models.CharField(max_length=100, blank=True, null=True)
    like_count = models.IntegerField(default=0, null=True)
    place = models.ForeignKey(Place)  # ,related_name='place_crosspictures')
    longitude = models.FloatField(blank=True, null=True)
    latitude = models.FloatField(blank=True, null=True)
    altitude = models.FloatField(blank=True, null=True, default=0.0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('datetime',)


class CityManager(models.Manager):

    def get_city(self, city_name, city_code, province_name=None, country_name=None):
        city_qs = self.filter(code=city_code)
        if city_qs:
            city = city_qs[0]
        else:
            if province_name:
                province = Province.objects.get_province(
                    province_name, country_name)
            else:
                province = None
            city = self.create(
                name=city_name, code=city_code, province=province)
        return city


class ProvinceManager(models.Manager):

    def get_province(self, province_name, country_name=None):
        province_qs = self.filter(name=province_name)
        if province_qs:
            province = province_qs[0]
        else:
            if country_name:
                country = Country.objects.get_country(country_name)
            else:
                country = None
            province = self.create(name=province_name, country=country)
        return province


class CountryManager(models.Manager):

    def get_country(self, country_name):
        country_qs = self.filter(name=country_name)
        if country_qs:
            country = country_qs[0]
        else:
            country = self.create(name=country_name)
        return country


class Country(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=100, null=True)

    objects = CountryManager()

    def __str__(self):
        return self.name


class Province(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=100, null=True)
    country = models.ForeignKey(Country, null=True)

    objects = ProvinceManager()

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=100, null=True)
    province = models.ForeignKey(Province, null=True)

    objects = CityManager()

    def __str__(self):
        return self.name

cross/views.py
from django.shortcuts import render_to_response
from django.http.response import HttpResponse
from django.views.generic.base import TemplateView
from . import models, serializers
from rest_framework import viewsets, permissions
from rest_framework.response import Response
from django.views.decorators.csrf import csrf_exempt
from PIL import Image
import numpy as np
import cv2
from django.views.decorators.cache import cache_page
#from django.conf import settings

#CACHE_TTL = getattr(settings, 'CACHE_TTL')


def home(request):
    return render_to_response('homepage.html')


def page_not_found(request):
    return render_to_response('404.html')


class PlaceViewSet(viewsets.ModelViewSet):
    queryset = models.Place.objects.all()
    serializer_class = serializers.PlaceSerializer
    permission_classes = [permissions.AllowAny]

    def list(self, request):
        place_name = request.GET.get('name')
        if place_name is not None:
            queryset = models.Place.objects.filter(name__contains=place_name)
        else:
            queryset = models.Place.objects.all()
        serializer = serializers.PlaceSerializer(queryset, many=True)
        return Response(serializer.data)


class CrossPictureViewSet(viewsets.ModelViewSet):
    queryset = models.CrossPicture.objects.all()
    serializer_class = serializers.CrossPictureSerializer
    permission_classes = [permissions.AllowAny]
#     permission_classes = [IsAccountAdminOrReadOnly]

"""
def compressImage(request):
    picture_list = models.CrossPicture.objects.all()
    for cp in picture_list:
        image = Image.open(cp.picture)
        width = image.width
        height = image.height
        rate = 1.0
        if width >= 2000 or height >= 2000:
            rate = 0.3
        elif width >= 1000 or height >= 1000:
            rate = 0.5
        elif width >= 500 or height >= 500:
            rate = 0.9
        width = int(width * rate)
        height = int(height * rate)
        image.thumbnail((width, height), Image.ANTIALIAS)
        image.save('media/' + str(cp.picture), 'JPEG')
        cp.save()
    return HttpResponse('compress finish')
"""

class place_list(TemplateView):
    template_name = 'place_list.html'

    def get(self, request, *args, **kwargs):        
        name = request.GET.get("name")
        if not name:
            place_list = models.Place.objects.all()
        else:
            place_list = models.Place.objects.filter(name__contains=name)
        context = {}
        context['place_list'] = place_list
        return self.render_to_response(context)


class picture_list(TemplateView):
    template_name = 'picture_list.html'
 
    def get_context_data(self,  **kwargs):        
        picture_list = models.CrossPicture.objects.all()
        context = {}
        context['picture_list'] = picture_list    
        return context


class add_place(TemplateView):
    template_name = 'add_place.html'

    def get(self, request, *args, **kwargs):
        name = request.GET.get("name")
        lng = request.GET.get("longitude")
        lat = request.GET.get("latitude")    
        place = None
        if name and lng and lat:            
            place = models.Place.objects.create(name=name, longitude=lng, latitude=lat)        
        
        context = {}
        context['result'] = place
        return self.render_to_response(context)

class add_picture(TemplateView):

    template_name = 'add_picture.html'
    
    """
    def get(self, request, *args, **kwargs):
        place_list = models.Place.objects.all()
        context = {}
        context['place_list'] = place_list
        return self.render_to_response(context)
    """

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        if request.method == "POST":            
            title = request.POST.get("title")
            picture = request.FILES.get("picture")
            datetime = request.POST.get("datetime")
            time_str = request.POST.get("time_str")
            detail_title = request.POST.get("detail_title")
            place_id = request.POST.get("place")
            longitude = request.POST.get("longitude")
            latitude = request.POST.get("latitude")

            place = models.Place.objects.get(id=place_id)   
            if not longitude:
                longitude = place.longitude
            if not latitude:
                latitude = place.latitude

            picture = models.CrossPicture(title=title, 
                            picture=picture, 
                            datetime=datetime, 
                            time_str=time_str, 
                            detail_title=detail_title, 
                            place=place, 
                            longitude=longitude, 
                            latitude=latitude)
            picture.save()            
            return HttpResponse("添加成功")
        elif request.method == "GET":
            place_list = models.Place.objects.all()
            context = {}
            context['place_list'] = place_list
            return self.render_to_response(context) 
 

class laboratory(TemplateView):

    template_name = 'laboratory.html'
    """
    def get_context_data(self, **kwargs):
        context = {}
        return self.render_to_response(context)
    """



@csrf_exempt
def similar_pictures(request):
    picture = request.FILES.get("picture")
    count = 0
    num = 20
    threshold = 12
    similar_list = []
    if picture:
        picture_list = models.CrossPicture.objects.all()
        for p in picture_list:
            if p.picture:
                similar = cal_similar(picture, p)
                if similar < threshold:
                    similar_list.append([p, similar])
                    count += 1
                if count >= num: break
    context = {}
    context['similar_list'] = similar_list
    return render_to_response('laboratory.html', {'similar_list': similar_list})


def cal_similar(p1, p2):
    image1 = np.array(Image.open(p1).convert('L'))
    image2 = np.array(Image.open(p2.picture).convert('L'))   
    h1 = p_hash(image1)
    h2 = p_hash(image2)
    return hamming(h1, h2)
        

def p_hash(src):        
    src = cv2.resize(src, (8, 8), cv2.INTER_LINEAR)
    avg = sum([sum(src[i]) for i in range(8)]) / 64
    string = ''
    for i in range(8):
        string += ''.join(map(lambda i: '0' if i < avg else '1', src[i]))    
    result = ''
    for i in range(0, 64, 4):
        result += ''.join('%x' % int(string[i: i + 4], 2))
    return result
        

def hamming(str1, str2):
    if len(str1) != len(str2): return
    count = 0
    for i in range(0, len(str1)):
        if str1[i] != str2[i]:
            count += 1
    return count 


class place_show(TemplateView):
    template_name = 'place_show.html'

    def get(self, request, id, *args, **kwargs):
        place = models.Place.objects.get(id=id)
        context = {}
        context['place'] = place  
        return self.render_to_response(context)

cross/templates/add_picture.html
<script type="text/javascript">

    function add() {
        if(!$("#title").val()){            
            $("#title").css("border-color", "#f90");
            alert("Picture Title 不能为空");
        }else if(!$("#picture").val()) {
            $("#picture").css("border-color", "#f90");
            alert("Picture 不能为空，你要选择一个图片文件");
        }else if(!$("#datetime").val()) {
            $("#datetime").css("border-color", "#f90");
            alert("Datetime 不能为空");
        }else if(!$("#timestr").val()) {
            $("#timestr").css("border-color", "#f90");
            alert("Place 不能为空");
        }else if(!$("#place").val()) {
            $("#place").css("border-color", "#f90");
            alert("Picture Title 不能为空");
        }else {            
            $("#form").submit();
        }
    }

</script>

{% extends "base.html" %}

{% block content %}
  <div class="container-fluid content">

    {% include "nav.html" %}  
    <script type="text/javascript">
      $(document).ready(function () {
        $("#nav_add_picture").attr("class", "active");
      });
    </script>
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
	<form id="form" method="post" action="../add_picture/" enctype="multipart/form-data">
          <div class="form-group">
            <label for="title">Picture Title</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="Picture Title">
          </div>        
          <div class="form-group">
            <label for="picture">Picture</label>
            <input type="file" accept="image/*" id="picture" name="picture">
          </div>
          <div class="form-group">
            <label for="datetime">Datetime</label>
            <input type="datetime-local" class="form-control" id="datetime" name="datetime" placeholder="Datetime">
          </div>
          <div class="form-group">          
            <label for="timestr">Time str</label>
            <input type="text" class="form-control" id="timestr" name="time_str" placeholder="Time str">
          </div>
          <div class="form-group">          
            <label for="detail_title">Detail title</label>
            <input type="text" class="form-control" id="detail_title" name="detail_title" placeholder="Detail title">
          </div>         
          <div class="form-group">          
            <label for="place">Place</label>
            <select class="form-control" id="place" name="place">
                {% for place in place_list %}
                  <script type="text/javascript">
                    var option = "<option value='{{place.id}}'>{{place.name}}</option>";
                    $("#place").append(option);
                  </script>
                {% empty %}
                <option value=''>null</option>
                {% endfor %}
            </select>
          </div>
          <div class="form-group">          
            <label for="longitude">Longitude</label>
            <input type="text" class="form-control" id="longitude" name="longitude" placeholder="Longitude">
          </div>
          <div class="form-group">          
            <label for="latitude">Latitude</label>
            <input type="text" class="form-control" id="latitude" name="latitude" placeholder="Latitude">
          </div>          
          <button type="submit" class="btn btn-default" onclick="add()">Submit</button>
        </form>
       {% if result %}
         {{ result }}	
       {% endif %}
      </div>
        
      <div class="col-md-2"></div>
    </div>
  </div>
</div>
<p></p>
{% endblock %}

cross/templates/add_place.html
<script type="text/javascript">
    function add() {
        if(!$("#name").val()) {
            alert("Place Name 不能为空");
            $("#name").css("border-color", "#f90");
        }else {
            $("#name").css("border-color", "");
                        
            if(!$("#longitude").val() || !$("#latitude").val()) {
                alert("经纬度不能为空");
                $("#longitude").css("border-color", "#f90");
                $("#latitude").css("border-color", "#f90");           
                 
            }else {
                $("#longitude").css("border-color", "");
                $("#latitude").css("border-color", "");            
                $("#form").submit();
            }             
        }


    }
</script>

{% extends "base.html" %}

{% block content %}
  <div class="container-fluid content">

    {% include "nav.html" %}  
    <script type="text/javascript">
      $(document).ready(function () {
        $("#nav_add_place").attr("class", "active");
      });
    </script>
    <div class="row">
      <div class="col-md-6">
	<form id="form" method="get" action="../add_place/">
          <div class="form-group">
            <label for="name">Place Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Place Name">
          </div>
          <p class="help-block"> 点击地图，确定经纬度</p>
          <div class="form-group">
            <label for="longitude">Longitude</label>
            <input type="text" class="form-control" id="longitude" name="longitude" placeholder="Longitude" readonly>
          </div>
          <div class="form-group">
            <label for="latitude">Latitude</label>
            <input type="text" class="form-control" id="latitude" name="latitude" placeholder="Latitude" readonly>
          </div>
  
          <button type="submit" class="btn btn-default" onclick="add()">Submit</button>
        </form>
        {% if result %}
           <p>刚刚成功添加了 {{ result }}</p>
        {% endif%}	
      </div>
        
      <div class="col-md-6">
        {% include "map.html" %}
        
        <script type="text/javascript">
          function addMarker(e) {
             map.clearOverlays();
             var marker = new BMap.Marker(e.point);
             map.addOverlay(marker);   
             $('#longitude').val(e.point.lng);
             $('#latitude').val(e.point.lat);            
          }
          map.addEventListener("click", addMarker);
        </script>
      </div>
    </div>
  </div>
</div>
<p></p>
{% endblock %}

cross/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="target-densitydpi=device-dpi, width=device-width, initial-scale=0.7, minimum-scale=0.5, maximum-scale=2, user-scalable=yes">
  <link  href="/static/bootstrap/css/bootstrap.min.css"  rel="stylesheet">
  <script src="/static/bootstrap/js/jquery-3.2.1.min.js"></script>
  <script src="/static/bootstrap/js/bootstrap.min.js"></script>
  <title>Dreamera</title>
  <style type="text/css">
    body,html {
       height:100%;
       padding-top:30px;
    }
  </style>
  </head>

  <body>
      {% block content %} (no content) {% endblock %}

      {% include "footer.html"%}
  </body>
</html>

cross/templates/footer.html
<footer class="footer" style="text-align:center;">
  <p>
      <span>&copy; Dreamera |</span>
      <span>by lijialin |</span>
      <a href="mailto:1040591521@qq.com" data-show-count="true" data-lang="en">
        Contact Dreamera
      </a>
  </p>
</footer>	  

cross/templates/homepage.html
<style type="text/css"> 
    #picture{
        text-align:center;
    }
</style>


{% extends "base.html" %}

{% block content %}
<div class="container-fluid content">

  {% include "nav.html" %}

  <div class="row">
    <div class="col-md-2"></div>

    <div class="col-md-4">                               
      <div class="carousel slide" id="carousel-231811" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-slide-to="0" data-target="#carousel-231811" class="active" ></li>
          <li data-slide-to="1" data-target="#carousel-231811" ></li>
          <li data-slide-to="2" data-target="#carousel-231811"></li>
        </ol>                        
        <div class="carousel-inner">
          <div class="item active">
            <center><img alt="" src="/static/android.png" /></center>
          </div>                        
          <div class="item">
            <center><img alt="" src="/static/android2.png" /></center>
          </div>                        
          <div class="item">
            <center><img alt="" src="/static/android3.png" /></center>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-4" id="picture">
      <h2>Welcome to Dreamera</h2>
      <h2>拍照后水印建筑物老照片</h2>
      <h2>Android v1.0<small>&emsp;浏览器扫码</small></h2>           
      <img src="/static/QRCode.png" alt="..." class="img-rounded">			
      <h2>Android v2.0<small>&emsp;浏览器扫码</small></h2>    
      <img src="/static/new_branch.png" alt="..." class="img-rounded">
    </div>	
            
    <div class="col-md-2"></div>
  </div>
</div>
      
{% endblock %}
{% include "footer.html" %} 
  

cross/templates/laboratory.html
<script type="text/javascript">
    function search() {
        if(!$("#picture").val()) {
            alert("未选择图片");
        }else {
            $("#form").submit();
        }
    }
</script>

{% extends "base.html" %}

{% block content %}
  <div class="container-fluid content">

    {% include "nav.html" %}  
    <script type="text/javascript">
      $(document).ready(function () {
        $("#nav_similar_pictures").attr("class", "active");
      });
    </script>

    <div class="row">
      <div class="alert alert-success" role="alert"> 
         <center>实验1：以图搜图,找到相似的图片</center>
      </div>
      <div class="col-md-2"></div>
      <div class="col-md-8">

	<form id="form" method="post" action="../similar_pictures/" enctype="multipart/form-data">
          <div class="form-group">
            <label for="picture">Input Picture</label>
            <input type="file" id="picture" accept="image/*" name="picture">
          </div>
          <button type="submit" class="btn btn-default" onclick="search()">Submit</button>
        </form>
      </div>
        
      <div class="col-md-2"></div>
    </div>

    <div class="row">
      {% for p in similar_list %}
        <div class="col-sm-8 col-md-4 col-ld-3">
          <center>
          <div class="caption">
              {% with image=p|first %}
              <img width='400' height='300' src="../media/{{image.picture}}"></img>
              <p>{{image}} 相似度:{{p|last}}</p>
              {% endwith %}
          </div>
          </center>
        </div>         
      {% empty %}
      <center><p>暂时没有数据哦</p> </center>
      {% endfor %}   
    </div>

    <div class="row">
      <div class="alert alert-success" role="alert"> 
         <center>实验2：仿照Prisma转换图片风格(没做呢)</center>
      </div>
      <div class="col-md-2"></div>
      <div class="col-md-8">

	<form id="form2" method="post" action="" enctype="multipart/form-data">
          <div class="form-group">
            <label for="picture">Input Picture</label>
            <input type="file" id="picture2" accept="image/*" name="picture2">
          </div>
          <button type="submit" class="btn btn-default" onclick="">Submit</button>
        </form>
      </div>
        
      <div class="col-md-2"></div>
    </div>

    <div class="row">
        <div class="col-sm-8 col-md-4 col-ld-3">
        </div>         
    </div>

  </div>

{% endblock %}

cross/templates/map.html
<style type="text/css">  
  #container {
    width:100%;
    height:1000px;
  }  
</style>  
<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=7TRXOG1TMCFqiMtlEndHbt4iRXp2rD5z">
</script>
<script type="text/javascript" src="http://api.map.baidu.com/library/TextIconOverlay/1.2/src/TextIconOverlay_min.js">
</script>
<script type="text/javascript" src="/static/bootstrap/js/MarkerClusterer_min.js"></script>

<div id="container"></div> 

<script type="text/javascript"> 
  var map = new BMap.Map("container");
  map.enableScrollWheelZoom(true);

  var control = new BMap.ScaleControl({anchor: BMAP_ANCHOR_BOTTOM_RIGHT});
  var navigation = new BMap.NavigationControl({anchor: BMAP_ANCHOR_BOTTOM_RIGHT}); 
  map.addControl(control);        
  map.addControl(navigation);  
  //map.setMapStyle({style:'grayscale'});  

  function locate(result){
    var cityName = result.name;
    map.centerAndZoom(cityName, 12);
  }
  var myCity = new BMap.LocalCity();
  myCity.get(locate);

  var markers = [];
  var pt = null;
  var marker = null;
  var label = null;
  var sContent = null;
  var picture_url = "http://www.dreamera.net:8080/media/";
</script>  

cross/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Dreamera</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">        
        <li id="nav_place_list"><a href="{% url 'place_list' %}">Places</a></li>
        <li id="nav_picture_list"><a href="{% url 'picture_list' %}">Pictures</a></li>
        <li id="nav_add_place"><a href="{% url 'add_place' %}">AddPlace</a></li>
        <li id="nav_add_picture"><a href="{% url 'add_picture' %}">AddPicture</a></li>
        <li id="nav_laboratory"><a href="{% url 'laboratory' %}">Laboratory</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li id="nav_sign_in"><a href="{% url 'account:sign_in' %}">Sign in or Sign up</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> 
            Github<span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="https://github.com/lijialinneu/GWS">Dreamera Server</a></li>
            <li><a href="https://github.com/lijialinneu/DreameraApp">Dreamera App</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

cross/templates/picture_list.html
{% extends "base.html" %}

{% block content %}

    <div class="container-fluid">
      {%include "nav.html"%}
      <script type="text/javascript">
        $(document).ready(function(){
          $("#nav_picture_list").attr("class","active");
        });
      </script>
      <div class="row">

      {% for picture in picture_list %}
	   <div class="col-sm-8 col-md-4 col-lg-3">	      
             <center>
	      <div class="caption">
	        {% if picture.picture %}
                  
		<img src="../../media/{{picture.picture}}" class="img-rounded" style="width:360px;height:270px;">
		{% else %}
		  <img src="" alt="...">
		{% endif %}
		<p>{{ picture }}</p>    
	      </div>
            </center>
	  </div>
	  {% empty %}
	  <center>  <h3><small>数据为空</small></h3></center>
      {% endfor %}


      </div>

    </div>
<p></p>
{% endblock %}

cross/templates/place_show.html
{% extends "base.html" %}

{% block content %}
  <div class="container-fluid content">

    {% include "nav.html" %}  
    <script type="text/javascript">
      $(document).ready(function () {
        $("#nav_place_list").attr("class", "active");
      });
    </script>
    
    <div class="row">
       <center>  <h3> {{ place.name }}</h3> </center>
    </div>
    <p></p>
    <div class="row">
      {% with picture_list=place.cross_pictures %}
        {% for picture in picture_list %}
          <div class="col-sm-8 col-md-4 col-lg-3">
            <center>
              <div class="caption">
                {% if picture %}
                  <img style="width:360px;height:270px;" src="../../media/{{picture.picture}}"></img>
                {% endif %}
                <p>{{ picture }}</p>
              </div>
            </center>
          </div>
          {% empty %}
          <center><h3><small>暂时没有数据哦</small> </h3>
          {% endfor %}    
        {% endwith %} 
    </div>

  </div>
</div>
<p></p>
{% endblock %}